# This workflow will verify any chall.yaml files it finds.
# For more information see: https://github.com/BCACTF/bcactf-2.0/pull/23#discussion_r626116130

name: Metadata verifier

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Get rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Install yaml verifier 
      run: cargo install --git https://github.com/BCACTF/arcs-yaml.git
    
    - name: Find changed
      uses: Stockopedia/action-get-changed-files@v1
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore: "{/*/**,/.github**}"
        foldersOnly: true
        format: csv
    
    - name: Verify YAML
      run: /bin/bash -c "arcs-yaml-parser $(echo "${{ steps.get_changed.outputs.changed }}" | awk -F', ' '{ for( i=1; i<=NF; i++ ) printf "%s ", $i"/chall.yaml" }')"
